function [t,s,f,g,h] = C_DepositionSolver(volumes,respiratory_settings,Y,max_size,mechanism,breaths,geom_mode,output,ratio)

% FOR FIGURES
set(groot,'defaultLineLineWidth',1, 'defaulttextInterpreter', 'latex', ...
     'defaultLegendInterpreter', 'latex')
set(groot,'defaultAxesTickLabelInterpreter','latex');
set(groot,'defaultAxesFontSize', 18)
set(groot,'defaultFigureColor',[1 1 1])
set(groot,'defaultLegendFontSize',18,'DefaultLegendFontSizeMode','manual')

mech = mechanism;
vol = volumes;
res = respiratory_settings;
par = F_Parameters();
Ppl0 = (vol.FRC-(par.Vut+par.Vub+par.Vuc+par.Vura))/(-(par.Cb+par.Cc+par.Cra));

% GET CONSTANT FLOWS AND VOLUMES
IC = [Ppl0 0 0 0 0]; % [Ppl Pt Pb Pc Pra]
dt = 10^-3;
tvals = 0:dt:res.T;
options = odeset('RelTol',10^-10);
[tt,ss] = ode15s(@(tt,ss) D_LungMechanicsODEs(tt,ss,par,Y,res,vol,geom_mode,ratio),tvals,IC,options);

Ppl = ss(:,1);
Pt = ss(:,2);
Pb = ss(:,3);
Pc = ss(:,4);
Pra = ss(:,5);

Vt = par.Ct*Pt+par.Vut; % volume of air in trachea
Vb = par.Cb*(Pb-Ppl)+par.Vub; % volume of air in bronchea
Vc = par.Cc*(Pc-Ppl)+par.Vuc; % volume of air in conducting airways
Vra = par.Cra*(Pra-Ppl)+par.Vura; % volume of air in respiratory airways
Vtotal = Vt+Vb+Vc+Vra;

tm = mod(tt,res.T);
for i = 1:length(tm)
    if tm(i)>=0 && tm(i)<=res.TI
        Pmus(i) = -res.Pmusmin*tm(i)^2/(res.TI*res.TE)+res.Pmusmin*res.T.*tm(i)/(res.TI*res.TE); % Pmus - pressure generated by respiratory muscles 
        u(i) = 1;
%         dPmus(i) = -2*res.Pmusmin*tt(i)/(res.TI*res.TE)+res.Pmusmin*res.T/(res.TI*res.TE);
    elseif tm(i)>res.TI && tm(i)<=res.T
%         Pmus(i) = -res.Pmusmin*tt(i)^2/(res.TI*res.TE)+res.Pmusmin*res.T.*tt(i)/(res.TI*res.TE);
        Pmus(i) = res.Pmusmin/(1-exp(-res.TE/res.tau))*(exp(-(tm(i)-res.TI)/res.tau)-exp(-res.TE/res.tau));
        u(i) = 0;
%         dPmus(i) = -2*res.Pmusmin*tt(i)/(res.TI*res.TE)+res.Pmusmin*res.T/(res.TI*res.TE);
%         dPmus(i) = res.Pmusmin/(1-exp(-res.TE/res.tau))*(-1/res.tau)*exp(-(tt(i)-res.TI)/res.tau);
    end
end
Pmus = Pmus(:);
Pcw = Ppl-Pmus;
Pel = Pra-Ppl;

% figure(80)
% hold on
% % yline(max(V),'--r','linewidth',1.5)
% % yline(min(V),'--r','linewidth',1.5)
% % pPcw = plot(Pcw,V,'-r','DisplayName','nonlinear compliance','linewidth',2);
% plot(Pcw_range,Vrange,'-k','DisplayName','nonlinear compliance');
% p = plot(Pcw_range(1:3:end),Vrange(1:3:end),'k>','HandleVisibility','off');
% p.MarkerFaceColor = 'k';
% 
% 
% % pPel = plot(Pel,V,'-r','DisplayName','nonlinear compliance','linewidth',2);
% % pPel.MarkerFaceColor = 'k';
% plot(Pel_range,Vrange,'-k','DisplayName','nonlinear compliance');
% p = plot(Pel_range(1:3:end),Vrange(1:3:end),'ko','HandleVisibility','off');
% p.MarkerFaceColor = 'k';
% 
% % pPsum = plot(Pcw+Pel,V,'-r','DisplayName','nonlinear compliance','linewidth',2);
% plot(Pcw_range+Pel_range,Vrange,'-.k','DisplayName','nonlinear compliance');
% p = plot(Pcw_range(1:3:end)+Pel_range(1:3:end),Vrange(1:3:end),'kd','HandleVisibility','off');
% p.MarkerFaceColor = 'k';

figure(80)
hold on
% plot(Pcw,Vra*1000)
% plot(Pel,Vtotal*1000)
% plot(Pcw+Pel,Vtotal*1000)

pPcw = plot(Pcw,Vtotal*1000,'-b','DisplayName','$P_{cw}$, constant');
% pPcw.MarkerFaceColor = 'w';

pPel = plot(Pel,Vtotal*1000,'--b','DisplayName','$P_{el}$, constant');
% pPel.MarkerFaceColor = 'w';

pPsum = plot(Pcw+Pel,Vtotal*1000,'-.b','DisplayName','$P_{cw}+P_{el}$, constant');
% pPsum.MarkerFaceColor = 'w';
legend box off location southeast

[Qin,Qex,Vin,Vex] = ConstantFlow(tt,ss,Y,vol,par,res,geom_mode,ratio);

% SET TIME STEP------------------------------------------------------------
dt = 10^-3;
% tvals = tinit(end):dt:breaths*res.T;
% tvals = 0:dt:breaths*res.TI;
tvals = 0:dt:breaths*res.T;

% SOLVE ODE SYSTEM=========================================================
%==========================================================================
dp_list1 = linspace(.01,.1,10);
dp_list2 = linspace(.2,1,9);
dp_list3 = linspace(2,10,9);

% dp_list1 = linspace(.01,.1,5);
% dp_list2 = linspace(.2,1,4);
% dp_list3 = linspace(2,10,4);
dp_list = [dp_list1 dp_list2 dp_list3]*10^-6; % particle sizes in meters

% Heyder1986 = readtable('data.xlsx','Sheet','Heyder1986','VariableNamingRule','preserve');
% x = Heyder1986.PD;
% x = x(find(x<=8));
% dp_list = x*10^-6;

% dp_list = 10*10^-6;

for i = 1:length(dp_list)
    dp = dp_list(i);
    options = odeset('RelTol',10^-10);
    tvals1 = 0:dt:res.T;
%     IC = [Ppl0 0 0 0 0 0 0 0 0 0 0 0 0];
    IC = [Ppl0 0 0 0 0 0 0 0 0 0 0 0 0 0 0];
    [t1,s1] = ode15s(@(t1,s1) D_DepositionODEs(t1,s1,par,Y,res,vol,dp,mechanism,...
            geom_mode,output,ratio,Qin,Qex,Vin,Vex),tvals1,IC,options);
    
    breaths=2;
    tvals2 = t1(end):dt:breaths*res.T;
    IC = s1(end,:);
    diff = 100;
    t = t1;
    s = s1;
    while diff>=.001
        [t2,s2] = ode15s(@(t2,s2) D_DepositionODEs(t2,s2,par,Y,res,vol,dp,mechanism,...
            geom_mode,output,ratio,Qin,Qex,Vin,Vex),tvals2,IC,options);
        t = [t; t2(2:end)];
        s = [s; s2(2:end,:)];

        % Pressures
        Ppl = s(:,1);
        Pt = s(:,2);
        Pb = s(:,3);
        Pc = s(:,4);
        Pra = s(:,5);
        
        Vt = par.Ct*Pt+par.Vut; % volume of air in trachea
        Vb = par.Cb*(Pb-Ppl)+par.Vub; % volume of air in bronchea
        Vc = par.Cc*(Pc-Ppl)+par.Vuc; % volume of air in conducting airways
        Vra = par.Cra*(Pra-Ppl)+par.Vura; % volume of air in respiratory airways
        Vtotal = Vt+Vb+Vc+Vra;

        Nt = s(:,6);
        Nb = s(:,8);
        Nc = s(:,10);
        Nra = s(:,12);
        Ntotal = Nt+Nb+Nc+Nra;

        Tind = find(abs((breaths-1)*res.T-t)==min(abs((breaths-1)*res.T-t)));
        diff = abs(Ntotal(end)/Vtotal(end)/par.Cin-Ntotal(Tind)/Vtotal(Tind)/par.Cin);

%         figure(60)
%         plot(t,(Ntotal./Vtotal)./par.Cin)
%         hold on
%         plot(t(end),(Ntotal(end)./Vtotal(end))./par.Cin,'ko')
%         plot(t(Tind),(Ntotal(Tind)./Vtotal(Tind))./par.Cin,'ro')
%         pause

        breaths = breaths+1;
        tvals2 = t2(end):dt:breaths*res.T;
        IC = s2(end,:);    
    end
    [f(:,i),g(:,i)] = G_CalculateDeposition(t,s,dp,par,res,Y,vol,mech,geom_mode,breaths-1,output,ratio,Qin,Qex,Vin,Vex);
end

figure(1)
hold on
p5 = plot(dp_list*10^6,f(12,:),'-k>','MarkerSize',6,'DisplayName','dynamic');
p5.MarkerFaceColor='w';
set(gca,'XScale','log')
set(gca, 'YTick',0:0.1:1,'XTick',[10^-2 10^-1 10^0 10])
set(gcf,'Color',[1 1 1])
ylabel('$\eta_{total}$')
xlabel('Particle Size ($\mu$m)')
legend box off
grid on
ylim([0 1])

figure(2)
hold on
p3 = plot(dp_list*10^6,f(7,:)+f(8,:)+f(9,:),'-ks','MarkerSize',6,'DisplayName','dynamic');
p3.MarkerFaceColor='w';
set(gca,'XScale','log')
set(gca, 'YTick',0:0.1:1,'XTick',[10^-2 10^-1 10^0 10])
set(gcf,'Color',[1 1 1])
ylabel('$\eta_{tr}+\eta_b+\eta_c$')
grid on
ylim([0 1])

figure(21)
hold on
p3 = plot(dp_list*10^6,f(7,:)+f(8,:),'-ks','MarkerSize',6,'DisplayName','dynamic');
p3.MarkerFaceColor='w';
set(gca,'XScale','log')
set(gca, 'YTick',0:0.1:1,'XTick',[10^-2 10^-1 10^0 10])
set(gcf,'Color',[1 1 1])
ylabel('$\eta_{tr}+\eta_b$')
grid on
ylim([0 1])

figure(3)
hold on
p4 = plot(dp_list*10^6,f(10,:)+f(11,:),'-ko','MarkerSize',6,'DisplayName','dynamic');
p4.MarkerFaceColor='w';
set(gca,'XScale','log')
set(gca, 'YTick',0:0.1:1,'XTick',[10^-2 10^-1 10^0 10])
set(gcf,'Color',[1 1 1])
ylabel('$\eta_{ra}$')
xlabel('Particle Size ($\mu$m)')
legend box off
grid on
ylim([0 1])

figure(4)
hold on
p4 = plot(dp_list*10^6,g(12,:),'-k>','MarkerSize',6,'DisplayName','dynamic');
p4.MarkerFaceColor='w';
set(gca,'XScale','log')
set(gca, 'YTick',0:0.1:1,'XTick',[10^-2 10^-1 10^0 10])
set(gcf,'Color',[1 1 1])
ylabel('$\alpha_{total}$')
xlabel('Particle Size ($\mu$m)')
legend box off
grid on
ylim([0 1])

figure(5)
hold on
p4 = plot(dp_list*10^6,g(7,:)+g(8,:)+g(9,:),'-ks','MarkerSize',6,'DisplayName','dynamic');
p4.MarkerFaceColor='w';
set(gca,'XScale','log')
set(gca, 'YTick',0:0.1:1,'XTick',[10^-2 10^-1 10^0 10])
set(gcf,'Color',[1 1 1])
ylabel('$\alpha_{tr}+\alpha_b+\alpha_c$')
xlabel('Particle Size ($\mu$m)')
legend box off
grid on
ylim([0 1])

figure(6)
hold on
p4 = plot(dp_list*10^6,g(10,:)+g(11,:),'-ko','MarkerSize',6,'DisplayName','dynamic');
p4.MarkerFaceColor='w';
set(gca,'XScale','log')
set(gca, 'YTick',0:0.1:1,'XTick',[10^-2 10^-1 10^0 10])
set(gcf,'Color',[1 1 1])
ylabel('$\alpha_{ra}$')
xlabel('Particle Size ($\mu$m)')
legend box off
grid on
ylim([0 1])

figure(7)
hold on
p4 = plot(dp_list*10^6,f(10,:)+f(11,:)+g(10,:)+g(11,:),'-ko','MarkerSize',6,'DisplayName','dynamic');
p4.MarkerFaceColor='w';
set(gca,'XScale','log')
set(gca, 'YTick',0:0.1:1,'XTick',[10^-2 10^-1 10^0 10])
set(gcf,'Color',[1 1 1])
ylabel('$\alpha_{ra}$')
xlabel('Particle Size ($\mu$m)')
legend box off
grid on
ylim([0 1])

%     breaths=2;
%     tvals2 = t1(end):dt:breaths*res.T;
%     IC = s1(end,:);
%     diff = 100;
%     t = t1;
%     s = s1;
%     while diff>=.001
%         [t2,s2] = ode15s(@(t2,s2) D_DepositionODEs(t2,s2,par,Y,res,vol,dp,mechanism,...
%             geom_mode,output,ratio,Qin,Qex,Vin,Vex),tvals2,IC,options);
%         t = [t; t2(2:end)];
%         s = [s; s2(2:end,:)];
% 
%         % Pressures
%         Ppl = s(:,1);
%         Pt = s(:,2);
%         Pb = s(:,3);
%         Pc = s(:,4);
%         Pra = s(:,5);
%         
%         Nt = s(:,6);
%         Nb = s(:,8);
%         Nc = s(:,10);
%         Nra = s(:,12);
%         Ntotal = Nt+Nb+Nc+Nra;
% %             Nalv = s(:,14);
% %             Ntotal = Nt+Nb+Nc+Nra+Nalv;
% 
%         Vt = par.Ct*Pt+par.Vut; % volume of air in trachea
%         Vb = par.Cb*(Pb-Ppl)+par.Vub; % volume of air in bronchea
%         Vc = par.Cc*(Pc-Ppl)+par.Vuc; % volume of air in conducting airways
%         Vra = par.Cra*(Pra-Ppl)+par.Vura; % volume of air in respiratory airways
%         Vtotal = Vt+Vb+Vc+Vra;
% %             VA = par.Cra*(Pra-Ppl)+par.Vura; % volume of air in respiratory airways
% %             Vtotal = Vt+Vb+Vc+VA;
%         
%         Tind = find(abs((breaths-1)*res.T-t)==min(abs((breaths-1)*res.T-t))); % index at end of first breath
% %             plot(t,(Ntotal./Vtotal)/par.Cin)
% %             hold on
% %             plot(t(end),Ntotal(end)/Vtotal(end)/par.Cin,'ko')
% %             plot(t(Tind),Ntotal(Tind)/Vtotal(Tind)/par.Cin,'ko')
% %             pause
%         diff = abs(Ntotal(end)/Vtotal(end)/par.Cin-Ntotal(Tind)/Vtotal(Tind)/par.Cin);
%         
% %             diff = abs((Nra(end)+Nalv(end))/VA(end)/par.Cin-(Nra(Tind)+Nalv(Tind))/VA(Tind)/par.Cin);
% %             diff=abs(s(end,12)-s(Tind,12));
% %             figure(2)
% %             hold on
% %             plot(t,(s(:,12)/Vra(end))/par.Cin,t(end),(s(end,12)/Vra(end))/par.Cin,'ro',t(Tind),(s(Tind,12)/Vra(Tind))/par.Cin,'bo')
% %             plot(t(end),s(end,12),'ro')
% %             plot(t(Tind),s(Tind,12),'bo')
% %             plot(t2,Ntotal)
% %             plot(t2(end),Ntotal(end),'ro')
% %             plot(t2(Tind),Ntotal(Tind),'bo')
% %             pause
%         breaths = breaths+1;
%         tvals2 = t2(end):dt:breaths*res.T;
%         IC = s2(end,:);    
%     end
% 
% %         figure(11)
% %         plot(t,((s(:,6)+s(:,7))./Vt+(s(:,8)+s(:,9))./Vb+(s(:,10)+s(:,11))./Vc)/par.Cin)
% %         hold on
% % 
% %         figure(12)
% %         hold on
% %         plot(t,((s(:,12)+s(:,13))./Vra)/par.Cin)
% % %         stop
% % 
% %         figure(13)
% %         hold on
% %         plot(t,(s(:,13)./Vra)/par.Cin)
% %         stop
%     
%     saturation(i) = breaths-1;
%     [f(:,i),g(:,i),h(:,i)] = G_CalculateDeposition(t,s,dp,par,res,Y,vol,mech,geom_mode,breaths-1,output,ratio,Qin,Qex,Vin,Vex);
% end
% 
% %     figure(100)
% %     plot(dp_list(1:2:end)*10^6,saturation(1:2:end),'-kx','MarkerSize',10)
% %     grid on
% %     xlabel('Particle Size ($\mu$m)')
% %     ylabel('Breathing Cycles')
% %     set(gca,'XScale','log')
% %     set(gca,'XTick',[10^-2 10^-1 10^0 10])
% %     set(gcf,'Color',[1 1 1])
% %     stop
% %     set(gca, 'YTick',0:2:18,'XTick',0:1:10)
% %     stop
% else
% for i = 1:length(dp_list)
% dp = dp_list(i);
% %     dp = 0.05*10^-6;
% options = odeset('RelTol',10^-10);
% 
% [t,s] = ode15s(@(t,s) D_DepositionODEs(t,s,par,Y,res,vol,dp,mechanism,geom_mode,output,ratio,Qin,Qex,Vin,Vex),tvals,IC,options);
% %     plot(t,s(:,11))
% %     stop
% [f(:,i),g(:,i),h(:,i)] = G_CalculateDeposition(t,s,dp,par,res,Y,vol,mech,geom_mode,breaths,output,ratio,Qin,Qex,Vin,Vex);
% end




end
